accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
    path('<str:username>/profile_update/', login_required(views.ProfileUpdateView.as_view()), name='profile_update'),
    path('<str:username>/followerswings/', views.followerswings, name='followerswings'),
    path('<str:username>/account_update/', login_required(views.AccountUpdateView.as_view()), name='account_update'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('community/', views.community, name='community'),
    path('<int:movie_pk>/review_form/', views.review_form, name="review_form"),
    path('<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comment_create/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/movie_detail/', views.movie_detail, name='movie_detail'),
    path('recommend1/', views.recommend1, name='recommend1'),
    path('recommend1/<int:genre_pk>/', views.recommend2, name='recommend2'),
    path('recommend1/<int:genre_pk>/<str:nation>/', views.recommend3, name='recommend3'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/', views.recommend4, name='recommend4'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/<str:vote>/', views.recommend_result, name='recommend_result'),
    path('recommend1/anything/', views.recommend_anything, name='recommend_anything'),
    path('recommend/<int:pk>/', views.recommend_genre, name='recommend_genre'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField(auto_now_add=True)
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=100)
    backdrop_path = models.CharField(blank=True, max_length=100)
    genres = models.ManyToManyField(Genre, related_name="movie_genre")
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews', blank=True)


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

movies/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'rank', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Genre, Review, Comment
from .forms import ReviewForm, CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q
from decouple import config

# Create your views here.

def index(request):
    movies = Movie.objects.order_by('?')
    genres = Genre.objects.order_by('name')
    MOVIES_API = config('MOVIES_API')

    context = {
        'movies': movies,
        'genres': genres,
        'MOVIES_API': MOVIES_API,
    }

    return render(request, 'movies/index.html', context)

def community(request):
    reviews = Review.objects.order_by('-created_at') ###
    paginator = Paginator(reviews, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'reviews': reviews,
        'page_obj': page_obj,
    }
    return render(request, 'movies/community.html', context)

@login_required
def review_form(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)

    if request.method == "POST":
        form = ReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.movie_title = movie
            review.user = request.user
            review.save()
            return redirect('movies:movie_detail', movie_pk)

    else:
        form = ReviewForm()

    context = {
        'form': form
    }
    return render(request, 'movies/review_form.html', context)

@login_required
def review_detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()

    context = {
        'review': review,
        'comment_form': comment_form,
    }
    return render(request, 'movies/review_detail.html', context)

@require_POST
@login_required
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        review.delete()

    return redirect('movies:community')


@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == "POST":
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('movies:review_detail', review.pk)

        else:
            form = ReviewForm(instance=review)
        context = {
            'form': form
        }
        return render(request, 'movies/review_form.html', context)
    else:
        return redirect('movies:index')

@login_required
def like(request, review_pk):
    user = request.user
    review = get_object_or_404(Review, pk=review_pk)

    if review.like_users.filter(pk=user.pk).exists():
        review.like_users.remove(user)
        liked = False
    else:
        review.like_users.add(user)
        liked = True

    context = {
        'liked': liked,
        'count': review.like_users.count(),
    }
    return JsonResponse(context)

@login_required
def comment_create(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()

    return redirect('movies:review_detail', review_pk)

@login_required
def comment_delete(request, review_pk, comment_pk):
    if request.method == "POST":
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()

    return redirect('movies:review_detail', review_pk)

def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    reviews = movie.review_set.all().order_by('-review.created_at')

    context = {
        'reviews': reviews,
        'movie': movie,
    }
    return render(request, 'movies/movie_detail.html', context)

@login_required
def recommend1(request):
    genres = Genre.objects.order_by('name')

    context = {
        'genres': genres,
    }
    return render(request, 'movies/recommend1.html', context)

@login_required
def recommend2(request, genre_pk):
    genre = Genre.objects.get(pk=genre_pk)
    genre_movies = []

    for movie in Movie.objects.all():
        if genre in movie.genres.all():
            genre_movies.append(movie)

    context = {
        'genre': genre,
        'genre_movies': genre_movies,
    }
    return render(request, 'movies/recommend2.html', context)

@login_required
def recommend3(request, genre_pk, nation):
    genre = Genre.objects.get(pk=genre_pk)
    nation_movies = []

    if nation == 'ko':
        for movie in Movie.objects.filter(original_language='ko'):
            if genre in movie.genres.all():
                nation_movies.append(movie)
    else:
        for movie in Movie.objects.filter(~Q(original_language='ko')):
            if genre in movie.genres.all():
                nation_movies.append(movie)

    context = {
        'genre': genre,
        'nation_movies': nation_movies,
        'nation': nation,
    }
    return render(request, 'movies/recommend3.html', context)

@login_required
def recommend4(request, genre_pk, nation, popular):
    genre = Genre.objects.get(pk=genre_pk)
    popular_movies = []

    if popular == 'yes':
        if nation == 'ko':
            for movie in Movie.objects.filter(original_language='ko').order_by('-popularity'):
                if genre in movie.genres.all():
                    popular_movies.append(movie)
        else:
            for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('-popularity'):
                if genre in movie.genres.all():
                    popular_movies.append(movie)
    else:
        if nation == 'ko':
            for movie in Movie.objects.filter(original_language='ko').order_by('?'):
                if genre in movie.genres.all():
                    popular_movies.append(movie)
        else:
            for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('?'):
                if genre in movie.genres.all():
                    popular_movies.append(movie)

    context = {
        'genre': genre,
        'popular_movies': popular_movies,
        'nation': nation,
        'popular': popular,
    }

    return render(request, 'movies/recommend4.html', context)

@login_required
def recommend_result(request, genre_pk, nation, popular, vote):
    genre = Genre.objects.get(pk=genre_pk)
    result_movies = []

    if vote == 'yes':
        if popular == 'yes':
            if nation == 'ko':
                for movie in Movie.objects.filter(original_language='ko').order_by('-vote_average', '-popularity'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
            else:
                for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('-vote_average', '-popularity'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
        else:
            if nation == 'ko':
                for movie in Movie.objects.filter(original_language='ko').order_by('-vote_average'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
            else:
                for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('-vote_average'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
    else:
        if popular == 'yes':
            if nation == 'ko':
                for movie in Movie.objects.filter(original_language='ko').order_by('-popularity'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
            else:
                for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('-popularity'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
        else:
            if nation == 'ko':
                for movie in Movie.objects.filter(original_language='ko').order_by('?'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
            else:
                for movie in Movie.objects.filter(~Q(original_language='ko')).order_by('?'):
                    if genre in movie.genres.all():
                        result_movies.append(movie)
    count = len(result_movies)
    context = {
        'genre': genre,
        'result_movies': result_movies[:3] if count > 3 else result_movies,
        'count': count,
    }
    return render(request, 'movies/recommend_result.html', context)

@login_required
def recommend_anything(request):
    movies = Movie.objects.order_by('?')[:3]

    context = {
        'movies': movies,
    }
    return render(request, 'movies/recommend_anything.html', context)

@login_required
def recommend_genre(request, pk):
    genre = Genre.objects.get(pk=pk)
    movies = []
    count = 0
    for movie in Movie.objects.order_by('-vote_count'):
        if count > 2:
            break

        if genre in movie.genres.all():
            movies.append(movie)
            count += 1
    context = {
        'genre': genre,
        'movies': movies,
        'count': count,
    }
    return render(request, 'movies/recommend_genre.html', context)

movies/templates/movies/community.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block content %}
<style>
	.pagination {
		justify-content: center;
	}
	
</style>
<h1 class="font-weight-bold text-center" style="font-family: sans-serif; color: firebrick;">Commuity</h1>

<hr>
<table class="table text-white">
	<thead>
		<tr>
			<th scope="col">영화 제목</th>
			<th scope="col">리뷰</th>
			<th scope="col">평점</th>
			<th scope="col">작성자</th>
			<th scope="col">작성 시간</th>
		</tr>
	</thead>

{% for review in page_obj %}
	<tbody>
		<tr>
			<td>
				<a href="{% url 'movies:movie_detail' review.movie_title.pk %}" style="color: firebrick; font-weight: bold;">{{ review.movie_title.title }}</a></td>
			</td>
			<td><a href="{% url 'movies:review_detail' review.pk %}" class="text-white">{{ review.title }}</a></td>
			<td>{{ review.rank }}</td>
			<td><a href="{% url 'accounts:profile' review.user.username %}" style="color: firebrick; font-weight: bold;">{{ review.user }}</a></td>
			<td>{{ review.created_at }}</td>
		</tr>
	</tbody>
{% endfor %}
</table>
 
<a href="/movies" style="color: firebrick;">Back</a>

{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}

<div class="pagination d-flex justfy-content-center">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page=1" style="color: firebrick;">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}" style="color: firebrick;">previous</a>
    {% endif %}

    <span class="current text-white">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" style="color: firebrick;">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}" style="color: firebrick;">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load list_shuffle %}

{% block content %}
<!-- <img src="/media/logo.gif" height="300" alt=""> -->
<div class="text-center">
  <a class="btn btn-outline-light mb-4" href="#" role="button">#NOW PLAYING</a>
<br>
<div class="nowplayings align-items-center"></div>
<br>
<a class="btn btn-outline-light mb-4" href="#" role="button">#TOP3</a>
<br>
<div class="todaymovies"></div>

<hr>
{% for genre in genres %}
  {% if genre.movie_genre.all.count != 0 %}
  <h4>
    <a href="{% url 'movies:recommend_genre' genre.pk %}" class="btn btn-outline-light">#{{ genre.name }}</a>
  </h4>
  <br>
  <div>
    {% for mov in genre.movie_genre.all|shuffle_list %}
      <div class="card text-white d-inline-flex m-0 p-0" style="width: 18vw; background-color: black;">
        <a href="{% url 'movies:movie_detail' mov.pk %}">
            <img class="w-100" src="https://image.tmdb.org/t/p/w342/{{ mov.poster_path }}" alt="movie_poster" style="height: 27vw;">
        </a>
        <div class="card-body">
          <span class="text-light">{{ mov.title }}</span>
          <span class="badge badge-pill badge-secondary">{{ mov.vote_average }}</span> 
          <a class="btn btn-outline-danger ml-2 rounded-lg" href="{% url 'movies:movie_detail' mov.pk %}" role="button">i</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <hr>
  {% endif %}
{% endfor %}
<hr>
</div>

<script>
  window.addEventListener('load', function(event){
    axios.get('https://api.themoviedb.org/3/movie/top_rated?api_key={{MOVIES_API}}&language=ko-KR&page=1&region=KR')
    .then(function(response){
      // console.log(response.data.results)
      const todayMovies = document.querySelector('.todaymovies')
      results = response.data.results
      for (var i=0; i<3; i++) {
        const movieUrl = results[i].poster_path
        const moviePosterLink = document.createElement('a')
        const moviePoster = document.createElement('img')
        moviePosterLink.setAttribute('href', `${results[i].id}/movie_detail/`)
        moviePoster.src = `https://image.tmdb.org/t/p/w342/${movieUrl}`
        moviePoster.style.height = '27vw'
        moviePosterLink.append(moviePoster)
        todayMovies.append(moviePosterLink)
      }
      // console.log(response.data.results[0].title)
      // console.log(response.data.results[0].poster_path)
    })
    .catch(function(error){
      console.log(error)
    })
  })
  window.addEventListener('load', function(event){
    axios.get('https://api.themoviedb.org/3/movie/now_playing?api_key={{MOVIES_API}}&language=ko-KR&page=1')
    .then(function(response){
      // console.log(response.data.results)
      const nowPlayings = document.querySelector('.nowplayings')
      results = response.data.results
      for (var i=0; i<3; i++) {
        console.log(results[i].id)
        const playUrl = results[i].poster_path
        const playPosterLink = document.createElement('a')
        const playPoster = document.createElement('img')
        playPosterLink.setAttribute('href', `${results[i].id}/movie_detail/`)
        playPoster.src = `https://image.tmdb.org/t/p/w342/${playUrl}`
        playPoster.style.height = '27vw'
        playPosterLink.append(playPoster)
        nowPlayings.append(playPosterLink)
      }
      // console.log(response.data.results[0].title)
      // console.log(response.data.results[0].poster_path)
    })
    .catch(function(error){
      console.log(error)
    })
  })

</script>

{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
  a {
    color:firebrick;
  }
</style>
<div class="text-center">
  <img class="mx-auto"src="https://image.tmdb.org/t/p/w342/{{ movie.backdrop_path }}" alt="movie_poster" style="width: 20rem;">
  <h2>{{ movie.title }} - {{ movie.original_title }}</h2>
  <div style="color: DarkGray">
    <p>{{ movie.release_date }}</p>
    {% for genre in movie.genres.all %}
    <span>{{ genre.name }}/</span>
    {% endfor %}
  </div>
</div>

<p style="color: DarkGray">{{ movie.overview }}</p>
<a href="{% url 'movies:review_form' movie.pk %}">NEW</a>

<hr>
<table class="table text-center text-white">
  <thead>
    <tr>
      <th scope="col">리뷰 제목</th>
      <th scope="col">평점</th>
      <th scope="col">작성자</th>
      <th scope="col">작성 시간</th>

    </tr>
  </thead>

{% for review in movie.review_set.all %}
  <tbody>
    <tr>
      <td><a href="{% url 'movies:review_detail' review.pk %}">{{ review.title }}</a></td>
      <td>{{ review.rank }}</td>
      <td><a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></td>
      <td>{{ review.created_at }}</td>
    </tr>
  </tbody>
{% endfor %}
</table>
<a href="/movies/">BACK</a>


{% endblock %}

movies/templates/movies/recommend1.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    {{ user.username }}님을 위한 추천영화
  </p>
</div>
<div class="progress mb-3 bg-dark">
  <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
</div>
<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    추천을 위해 몇 가지 질문을 드리겠습니다.
  </p>
  <p class="font-weight-bold" style="font-size: 2vw;">
    어떤 장르의 영화를 원하시나요?
  </p>
</div>
<div class="text-center">
  <div class="btn-toolbar d-inline-flex mx-auto" role="toolbar" aria-label="Toolbar with button groups">
    {% for genre in genres %}
    <div class="btn-group m-2" role="group" aria-label="First group">
      <a href="{% url 'movies:recommend2' genre.pk %}">
        <button type="button" class="btn btn-danger">
          {{ genre.name }}
        </button>
      </a>
    </div>
    {% endfor %}
  </div>
  <br>
  <br>
  <br>
  <div class="btn-toolbar d-inline-flex mx-auto" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group m-2" role="group" aria-label="Second group">
      <a href="{% url 'movies:recommend_anything' %}">
        <button type="button" class="btn btn-danger">
          아무거나
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

movies/templates/movies/recommend2.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    {{ user.username }}님을 위한 추천영화
  </p>
</div>
<div class="progress mb-3 bg-dark">
  <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"></div>
</div>
<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    다음 질문을 드리겠습니다.
  </p>
  <p class="font-weight-bold" style="font-size: 2vw;">
    한국영화를 원하시나요?
  </p>
</div>
<div class="btn-toolbar d-inline-flex mx-auto" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group m-2" role="group" aria-label="First group">
    <a href="{% url 'movies:recommend3' genre_pk=genre.pk nation='ko' %}">
      <button type="button" class="btn btn-danger">
        Yes
      </button>
    </a>
  </div>
  <div class="btn-group m-2" role="group" aria-label="Second group">
    <a href="{% url 'movies:recommend3' genre_pk=genre.pk nation='nko' %}">
      <button type="button" class="btn btn-danger">
        No
      </button>
    </a>
  </div>
</div>



{% endblock %}

movies/templates/movies/recommend3.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    {{ user.username }}님을 위한 추천영화
  </p>
</div>
<div class="progress mb-3 bg-dark">
  <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"></div>
</div>
<div class="text-center text-danger my-3">
  <p class="font-weight-bold" style="font-size: 2vw;">
    이제 거의 다 왔어요!
  </p>
  <p class="font-weight-bold" style="font-size: 2vw;">
		유명한 영화를 원하시나요?
  </p>
</div>
<div class="btn-toolbar d-inline-flex mx-auto" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group m-2" role="group" aria-label="First group">
    <a href="{% url 'movies:recommend4' genre_pk=genre.pk nation=nation popular='yes' %}">
      <button type="button" class="btn btn-danger">
        Yes
      </button>
    </a>
  </div>
  <div class="btn-group m-2" role="group" aria-label="Second group">
    <a href="{% url 'movies:recommend4' genre_pk=genre.pk nation=nation popular='no' %}">
      <button type="button" class="btn btn-danger">
        No
      </button>
    </a>
  </div>
</div>

{% endblock %}

movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h5 class="font-weight-bold" style="font-family: sans-serif; color: firebrick;">Community</h5>
<br>
<h3>{{ review.title }}</h3>
<a href="{% url 'accounts:profile' review.user.username %}"><span style="color: DarkGray">{{ review.user.username }}</span></a>
<span class="float-right" style="color: DarkGray">{{ review.created_at }}</span>
<p class="text-right" style="color: DarkGray">{{ review.updated_at }} 수정됨</p>
<hr>

<ul class="list-group" style="color: black">
  <li class="list-group-item bg-dark text-white">{{ review.movie_title.title }}
    <span class="badge badge-danger ml-1">{{ review.rank }}</span>
  </li>
  <li class="list-group-item bg-dark text-white">{{ review.content }}</li>
</ul>

<a href="{% url 'movies:community' %}" style="color: firebrick;">Back</a>
<br>

{% if review.user == request.user %}
<div class="d-flex">
  <a href="{% url 'movies:update' review.pk %}">
    <button type="button" class="btn mr-2 text-white" style="background-color: firebrick;">수정</button>
  </a>

  <form action="{% url 'movies:delete' review.pk %}" method="POST">
  {% csrf_token %}
    <input class="btn text-white" style="background-color: firebrick;" type="submit" value="삭제">
  </form>
</div>
{% endif %}

{% if user.is_authenticated %}
    {% if user in review.like_users.all %}
      <i class="fas fa-heart fa-lg like-btn" data-pk="{{ review.pk }}" style="color:crimson"></i>
    {% else %}
      <i class="fas fa-heart fa-lg like-btn" data-pk="{{ review.pk }}" style="color:white"></i>
    {% endif %}
{% endif %}
  <span class="cnt-{{ review.pk }}">{{ review.like_users.all|length }}</span> 명이 이 글을 좋아합니다.
<hr>

{% for comment in review.comment_set.all %}
  <div class="container">
    <div class="row">
      <div class="col-2">
        {{ comment.user }}
      </div>
      <div class="col-6">
        {{ comment.content }}
      </div>
      <div class="col-3">
        {{ comment.created_at }}
      </div>
      <div class="col-1">
        <form action="{% url 'movies:comment_delete' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input class="btn btn-outline-secondary btn-sm" type="submit" value="댓글 삭제">
        </form>
      </div>
    </div>
  </div>  
  <hr>
{% endfor %}


<form action="{% url 'movies:comment_create' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn text-white" style="background-color: firebrick;">댓글쓰기</button>
</form>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const likeBtns = document.querySelectorAll('.like-btn')
  console.log(likeBtns)

  likeBtns.forEach(function(btn){
    btn.addEventListener('click', function(event){
      console.log(btn.dataset)
      axios.get(`/movies/${btn.dataset.pk}/like/`)
      .then(function(res){
        console.log(res)
        if (res.data.liked) {
          btn.style.color = 'crimson'
        } else {
          btn.style.color = 'white'
        }
        const cntSpan = document.querySelector(`.cnt-${btn.dataset.pk}`)
        console.log(cntSpan)
        cntSpan.innerText = res.data.count
      })
      .catch(function(err){
        console.log(err)
      })
    })
  })
</script>
{% endblock %}