accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
    path('<str:username>/profile_update/', login_required(views.ProfileUpdateView.as_view()), name='profile_update'),
    path('<str:username>/followerswings/', views.followerswings, name='followerswings'),
    path('<str:username>/account_update/', login_required(views.AccountUpdateView.as_view()), name='account_update'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('community/', views.community, name='community'),
    path('<int:movie_pk>/review_form/', views.review_form, name="review_form"),
    path('<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comment_create/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/movie_detail/', views.movie_detail, name='movie_detail'),
    path('recommend1/', views.recommend1, name='recommend1'),
    path('recommend1/<int:genre_pk>/', views.recommend2, name='recommend2'),
    path('recommend1/<int:genre_pk>/<str:nation>/', views.recommend3, name='recommend3'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/', views.recommend4, name='recommend4'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/<str:vote>/', views.recommend_result, name='recommend_result'),
    path('recommend1/anything/', views.recommend_anything, name='recommend_anything'),
    path('recommend/<int:pk>/', views.recommend_genre, name='recommend_genre'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit

# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')
    is_staff = models.BooleanField(default=False)

def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extenstion = filename.split('.')[-1]
    
    return '%s%s%s' % (instance.owner.username, pid, extenstion)

class Photo(models.Model):
    image = models.ImageField(upload_to=user_path)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    thumbnail_image = models.ImageField(blank=True)
    comment = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=40, blank=True)
    introduction = models.TextField(blank=True)
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
                        source='image', 
                        processors=[ResizeToFit(300, 300)],
                        format='JPEG',
                        options={'quality': 60}
                        )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Photo, Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name']

class ProfileForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction', 'image']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib.auth import get_user_model
from django.views.generic.detail import DetailView
from django.views import View
from movies.models import Review, Movie
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    reviews = Review.objects.filter(user=person).order_by('-created_at')

    context = {
        'person': person,
        'reviews': reviews,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, username):
    you = get_object_or_404(get_user_model(), username=username)
    me = request.user

    if me != you:
        if you. followers.filter(pk=me.pk).exists():
            you.followers.remove(me)
        else:
            you.followers.add(me)

    return redirect('accounts:profile', you.username)

class ProfileUpdateView(View):
    def get(self, request, username):
        user = get_object_or_404(get_user_model(), username=username)
        user_form = CustomUserCreationForm(initial={
            'first_name': user.first_name,
            'username': user.username,
        })

        if hasattr(user, 'profile'):
            profile = user.profile
            profile_form = ProfileForm(initial={
                'nickname': profile.nickname,
                'introduction': profile.introduction,
                'image': profile.image,
            })
        else:
            profile_form = ProfileForm()

        context = {
            "user_form": user_form,
            "profile_form": profile_form,
        }

        return render(request, 'accounts/profile_update.html', context)

    def post(self, request, username):
        person = get_object_or_404(get_user_model(), username=username)
        user_form = CustomUserCreationForm(request.POST, instance=person)

        if user_form.is_valid():
            user_form.save()

        if hasattr(person, 'profile'):
            profile = person.profile
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        else:
            profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = person
            profile.save()

        return redirect('accounts:profile', person.username)
        
def followerswings(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    
    context = {
        'person': person,
    }

    return render(request, 'accounts/followerswings.html', context)

class AccountUpdateView(View):
    def get(self, request, username):
        user = get_object_or_404(get_user_model(), username=username)
        user_form = CustomUserCreationForm(initial={
            'first_name': user.first_name,
            'username': user.username,
        })

        context = {
            "user_form": user_form,
        }

        return render(request, 'accounts/account_update.html', context)

    def post(self, request, username):
        person = get_object_or_404(get_user_model(), username=username)
        user_form = CustomUserCreationForm(request.POST, instance=person)

        if user_form.is_valid():
            user_form.save()
            update_session_auth_hash(request, person)

        return redirect('accounts:profile', person.username)

accounts/templates/accounts/account_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h1>account Update</h1>

<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form user_form %}
    <input class="btn btn-success" type="submit" value="Update"/>
</form>

{% endblock %}

accounts/templates/accounts/followerswings.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<p style="font-size: 3vw;">{{ person.username }}'s followers : {{ person.followers.all|length }}</p>
<hr class="bg-white mb-2">
{% for per in person.followers.all %}
<a href="{% url 'accounts:profile' per.username %}" style="color: firebrick; font-weight: bold;"><p class="m-0" style="font-size: 1vw;">{{ per.username }}</p></a>
{% endfor %}
<hr class="bg-white my-2">
<br>
<br>
<p style="font-size: 3vw;">{{ person.username }}'s followings : {{ person.followings.all|length }}</p>
<hr class="bg-white mb-2">
{% for per in person.followings.all %}
  <a href="{% url 'accounts:profile' per.username %}" style="color: firebrick; font-weight: bold;"><p class="m-0" style="font-size: 1vw;">{{ per.username }}</p></a>
{% endfor %}
<hr class="bg-white my-2">

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% load account socialaccount %}
{% load socialaccount %}
{% get_providers as socialaccount_providers %}

{% block content %}
<div class="w-50 m-auto">
  <br>
  <h1>{% trans "Sign In" %}</h1>
  <br>

  {% get_providers as socialaccount_providers %}

  <form class="login" method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <div class="text-center">
      <button class="primaryAction btn btn-danger w-100" type="submit">{% trans "Sign In" %}</button>
      
      <!-- {% if socialaccount_providers %}
      <div class="socialaccount_ballot">
    
        <ul class="socialaccount_providers list-unstyled text-danger">
          <!-- {% include "socialaccount/snippets/provider_list.html" with process="login" %} -->
        <!-- </ul>
    
      </div> -->
      <div class="socialaccount_ballot">
        <ul class="socialaccount_providers list-unstyled text-danger">
          {% for provider in socialaccount_providers %}
          <li class="list-style mt-2">
            {% if provider.name == 'Google' %}
              <a title="{{provider.name}}" class="socialaccount_provider {{provider.id}} text-white" 
                href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
                <button class="w-100 btn btn-primary" type="button">
                  {{provider.name}}
                </button>
              </a>
            {% elif provider.name == 'Kakao' %}
              <a title="{{provider.name}}" class="socialaccount_provider {{provider.id}} text-dark" 
                href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
                <button class="w-100 btn btn-warning" type="button">
                  {{provider.name}}
                </button>
              </a>
            {% else %}
              <a title="{{provider.name}}" class="socialaccount_provider {{provider.id}} text-white" 
                href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
                <button class="w-100 btn btn-dark" type="button">
                  {{provider.name}}
                </button>
              </a>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
      </div>
      


    
      {% include "socialaccount/snippets/login_extra.html" %}
    
      {% else %}
      <p>{% blocktrans %}If you have not created an account yet, then please
      <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
      {% endif %}
    </div>
    <a href="{% url 'accounts:signup' %}" class="button text-danger secondaryAction">아직 계정이 없으신가요?</a>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <br>
  <div class="text-center">
    <h1 class="text-center">{{ person.username }}</h1>
    {% if user == person %}
      <div class="text-center d-flex justify-content-center">
        <a class="mr-5" href="{% url 'accounts:profile_update' person.username %}" style="color: red;">
          Profile Edit
        </a>
        <a href="{% url 'accounts:account_update' person.username %}" style="color: red;">
          Account Edit
        </a>
      </div>
    {% endif %}

    {% if user != person %}
      {% if user in person.followers.all %}
      <a href="{% url 'accounts:follow' person.username %}"><button class="btn btn-success center" type="button">팔로우 취소</button></a>
      {% else %}
      <a href="{% url 'accounts:follow' person.username %}"><button class="btn btn-success center" type="button">팔로우</button></a>
      {% endif %}
    {% endif %}
  </div>
  <br>
  

  <div class="container">
    <div class="row">
        <div class="col-12 col-md-4 mb-4">
            {% if person.profile.image %}
              <img class="rounded-circle bg-white border border-white" src="{{ person.profile.image.url }}" style="width: 250px; height: 250px;">
              <br>
            {% else %}
              <img class="rounded-circle bg-white border border-white" src="/media/emptyprofile.png" style="width: 250px; height: 250px;">
              <br>
            {% endif %}
            
        </div>
        <div class="col-12 col-md-8 d-flex justify-content-center align-items-center">
          <ul class="list-group list-group-horizontal text-center">
            <li class="list-group-item bg-transparent border-0">
              <p style="font-size: 5vw;">{{ reviews|length}}</p>
            
              <p style="font-size: 3vw;">게시물</p>
            </li>
            <li class="list-group-item bg-transparent border-0">
              <a href="{% url 'accounts:followerswings' person.username %}" class="text-white"><p style="font-size: 5vw;">{{ person.followers.all|length }}</p></a>

              <p style="font-size: 3vw;">팔로워</p>
            </li>
            <li class="list-group-item bg-transparent border-0">
              <a href="{% url 'accounts:followerswings' person.username %}" class="text-white"><p style="font-size: 5vw;">{{ person.followings.all|length }}</p></a>

              <p style="font-size: 3vw;">팔로잉</p>
            </li>
          </ul>
        </div>
        {% if person.profile.introduction %}
          <hr class="bg-white my-2 w-100">
          <div>
              {{ person.profile.introduction }}
          </div>
          <hr class="bg-white mb-3 w-100">
        {% endif %}
    </div>
  </div>
  <br>

  <h3 class="mb-3">{{ person.username }}'s Review</h3>
  <table class="table">
    <thead class="bg-dark text-center text-white">
      <tr>
        <th scope="col">영화 제목</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">평점</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
  
  {% for review in reviews %}
    <tbody class="text-center text-white">
      <tr>
        <td>
          <a href="{% url 'movies:movie_detail' review.movie_title.pk %}" style="color: firebrick; font-weight: bold;">{{ review.movie_title.title }}</a></td>
        </td>
        <td><a href="{% url 'movies:review_detail' review.pk %}" style="color: firebrick; font-weight: bold;">{{ review.title }}</a></td>
        <td>{{ review.rank }}</td>
        <td>{{ review.created_at }}</td>
      </tr>
    </tbody>
  {% endfor %}
  </table>

{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h1>Profile Update</h1>

<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    <input class="btn btn-success" type="submit" value="Update"/>
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% load i18n %}
{% block content %}

<div class="w-50 m-auto">
  <br>
  <h1>{% trans "Sign Up" %}</h1>
  <br>
  
  <p>이미 계정이 있으신가요? 바로 <a href="{% url 'accounts:login' %}" class="text-danger">로그인</a> 하세요.</p>

  <form class="signup form" id="signup_form" method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <!-- {{ form.as_p }} -->
    {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    {% buttons %}
      <button type="submit" class="btn btn-danger w-100">{% trans "Sign Up" %} &raquo;</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

accounts/templates/accounts/upload.html
{% extends 'base.html' %}
{% block content %}

<h1>Upload</h1>

<form action="{% url 'accounts:upload' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Upload"/>
</form>

{% endblock %}