accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
    path('<str:username>/profile_update/', login_required(views.ProfileUpdateView.as_view()), name='profile_update'),
    path('<str:username>/followerswings/', views.followerswings, name='followerswings'),
    path('<str:username>/account_update/', login_required(views.AccountUpdateView.as_view()), name='account_update'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('community/', views.community, name='community'),
    path('<int:movie_pk>/review_form/', views.review_form, name="review_form"),
    path('<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comment_create/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/movie_detail/', views.movie_detail, name='movie_detail'),
    path('recommend1/', views.recommend1, name='recommend1'),
    path('recommend1/<int:genre_pk>/', views.recommend2, name='recommend2'),
    path('recommend1/<int:genre_pk>/<str:nation>/', views.recommend3, name='recommend3'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/', views.recommend4, name='recommend4'),
    path('recommend1/<int:genre_pk>/<str:nation>/<str:popular>/<str:vote>/', views.recommend_result, name='recommend_result'),
    path('recommend1/anything/', views.recommend_anything, name='recommend_anything'),
    path('recommend/<int:pk>/', views.recommend_genre, name='recommend_genre'),
]

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>SETFLIX</title>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://kit.fontawesome.com/c698631df4.js" crossorigin="anonymous"></script>
    {% bootstrap_css %}
    <style>
      body {
        color: white;
      }
    </style>
</head>
<body style="background-color: black;">
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: rgba(0, 0, 0, 0.616);">
      <a class="navbar-brand" href="{% url 'movies:index' %}">
        <img src="/media/setflix.png" height="50" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarTogglerDemo02">
        <div class="">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:index' %}">HOME</a>
            </li>
            <li class="nav-item">
							<a class="nav-link" href="{% url 'movies:community' %}">COMMUNITY</a>
            </li>
            <li class="nav-item">
							<a class="nav-link" href="{% url 'movies:recommend1' %}">RECOMMEND</a>
						</li>
          </ul>
        </div>
        {% if user.is_authenticated %}
        <div class="">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/accounts/logout">LOGOUT</a>
              <!-- <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a> -->
            </li>
            <li class="nav-item mt-2 mx-3 text-white">
              <a href="{% url 'accounts:profile' user.username %}" style="color: red;">{{ user.username }}</a>님 안녕하세요!</h2>
            </li>
          </ul>
        </div>
        {% else %}
        <div class="">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/accounts/login">LOGIN</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/accounts/signup">SIGN UP</a>
            </li>
          </ul>
        </div>
        {% endif %}
      </div>
    </nav>
    <div class="container justify-content-center w-75 m-auto">
      <img src="/media/setflix.png" alt="setflix" class="d-block mx-auto" style="height: 10vw;">
    {% block content %}
    {% endblock %}
    </div>


    {% bootstrap_javascript jquery='full' %}
</body>
</html>